[package]
name = "hpl-utils"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]
path = "src/lib.rs"

[dependencies]
anchor-lang = "0.26.0"
mpl-token-metadata = { version="1.8.0", features = [ "no-entrypoint" ] }